### ISSUE TITLE
add URLs after link text in print version?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/varnish#162]
In https://github.com/carpentries/docs.carpentries.org/issues/201, Owen asked about including URLs for links in the printed version of a lesson. [It looks like we could enable this](https://david.garden/how-to-display-links-in-print-mode-on-your-website/) with some relatively small changes to the CSS in varnish:

```css
@media print {
    a[href]:after {
        content: ' (' attr(href) ')';
    }
}
```

What are your thoughts about doing this? Any potential hazards that I am missing?
